package com.imm.model;

import java.util.Date;

public class OfflineMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.from
     *
     * @mbg.generated
     */
    private Integer from;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.to
     *
     * @mbg.generated
     */
    private Integer to;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.addTime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    public OfflineMessage(Integer id, Integer from, Integer to, String content, String status, Date addtime, Date updatetime) {
        this.id = id;
        this.from = from;
        this.to = to;
        this.content = content;
        this.status = status;
        this.addtime = addtime;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_message.id
     *
     * @return the value of offline_message.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_message.from
     *
     * @return the value of offline_message.from
     *
     * @mbg.generated
     */
    public Integer getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_message.to
     *
     * @return the value of offline_message.to
     *
     * @mbg.generated
     */
    public Integer getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_message.content
     *
     * @return the value of offline_message.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_message.status
     *
     * @return the value of offline_message.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_message.addTime
     *
     * @return the value of offline_message.addTime
     *
     * @mbg.generated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_message.updateTime
     *
     * @return the value of offline_message.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }
}