package com.imm.model.po;

import java.util.Date;

public class OfflineMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.messagefrom
     *
     * @mbg.generated
     */
    private Integer messagefrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.messageto
     *
     * @mbg.generated
     */
    private Integer messageto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.messagecontent
     *
     * @mbg.generated
     */
    private String messagecontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.messagestatus
     *
     * @mbg.generated
     */
    private String messagestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_message.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    public OfflineMessage() {
    }

    public Integer getId() {
        return id;
    }

    public OfflineMessage setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getMessagefrom() {
        return messagefrom;
    }

    public OfflineMessage setMessagefrom(Integer messagefrom) {
        this.messagefrom = messagefrom;
        return this;
    }

    public Integer getMessageto() {
        return messageto;
    }

    public OfflineMessage setMessageto(Integer messageto) {
        this.messageto = messageto;
        return this;
    }

    public String getMessagecontent() {
        return messagecontent;
    }

    public OfflineMessage setMessagecontent(String messagecontent) {
        this.messagecontent = messagecontent;
        return this;
    }

    public String getMessagestatus() {
        return messagestatus;
    }

    public OfflineMessage setMessagestatus(String messagestatus) {
        this.messagestatus = messagestatus;
        return this;
    }

    public Date getAddtime() {
        return addtime;
    }

    public OfflineMessage setAddtime(Date addtime) {
        this.addtime = addtime;
        return this;
    }

    public Date getUpdatetime() {
        return updatetime;
    }

    public OfflineMessage setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
        return this;
    }
}