package com.imm.model.po;

import java.util.Date;

public class Relation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.friendid
     *
     * @mbg.generated
     */
    private Integer friendid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relation.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    public Relation(){
    }

    public Integer getId() {
        return id;
    }

    public Relation setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getUserid() {
        return userid;
    }

    public Relation setUserid(Integer userid) {
        this.userid = userid;
        return this;
    }

    public Integer getFriendid() {
        return friendid;
    }

    public Relation setFriendid(Integer friendid) {
        this.friendid = friendid;
        return this;
    }

    public String getStatus() {
        return status;
    }

    public Relation setStatus(String status) {
        this.status = status;
        return this;
    }

    public Date getAddtime() {
        return addtime;
    }

    public Relation setAddtime(Date addtime) {
        this.addtime = addtime;
        return this;
    }

    public Date getUpdatetime() {
        return updatetime;
    }

    public Relation setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
        return this;
    }
}