package com.imm.model.po;

import java.util.Date;

public class Synch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column synch.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column synch.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column synch.transaction_code
     *
     * @mbg.generated
     */
    private String transactionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column synch.transaction_id
     *
     * @mbg.generated
     */
    private Integer transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column synch.transaction_event
     *
     * @mbg.generated
     */
    private String transactionEvent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column synch.transaction_status
     *
     * @mbg.generated
     */
    private Byte transactionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column synch.addtime
     *
     * @mbg.generated
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synch
     *
     * @mbg.generated
     */
    public Synch(){
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getTransactionCode() {
        return transactionCode;
    }

    public void setTransactionCode(String transactionCode) {
        this.transactionCode = transactionCode;
    }

    public Integer getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }

    public String getTransactionEvent() {
        return transactionEvent;
    }

    public void setTransactionEvent(String transactionEvent) {
        this.transactionEvent = transactionEvent;
    }

    public Byte getTransactionStatus() {
        return transactionStatus;
    }

    public void setTransactionStatus(Byte transactionStatus) {
        this.transactionStatus = transactionStatus;
    }

    public Date getAddtime() {
        return addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}