package com.imm.dao;

import com.imm.dao.base.MyBatisRepository;
import com.imm.model.OfflineMessage;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Component;

@Component
@MyBatisRepository
public interface OfflineMessageDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    @Delete({
        "delete from offline_message",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    @Insert({
        "insert into offline_message (id, from, ",
        "to, content, status, ",
        "addTime, updateTime)",
        "values (#{id,jdbcType=INTEGER}, #{from,jdbcType=INTEGER}, ",
        "#{to,jdbcType=INTEGER}, #{content,jdbcType=VARCHAR}, #{status,jdbcType=CHAR}, ",
        "#{addtime,jdbcType=TIMESTAMP}, #{updatetime,jdbcType=TIMESTAMP})"
    })
    int insert(OfflineMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    int insertSelective(OfflineMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, from, to, content, status, addTime, updateTime",
        "from offline_message",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.imm.dao.OfflineMessageDao.BaseResultMap")
    OfflineMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OfflineMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    @Update({
        "update offline_message",
        "set from = #{from,jdbcType=INTEGER},",
          "to = #{to,jdbcType=INTEGER},",
          "content = #{content,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=CHAR},",
          "addTime = #{addtime,jdbcType=TIMESTAMP},",
          "updateTime = #{updatetime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OfflineMessage record);
}