package com.imm.dao;

import com.imm.dao.base.MyBatisRepository;
import com.imm.model.OfflineMessage;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Component;

@Component
@MyBatisRepository
public interface OfflineMessageDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    @Delete({
        "delete from offline_message",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    @Insert({
        "insert into offline_message (id, message_from, ",
        "message_to, message_content, ",
        "message_status, addTime, ",
        "updateTime)",
        "values (#{id,jdbcType=INTEGER}, #{messageFrom,jdbcType=INTEGER}, ",
        "#{messageTo,jdbcType=INTEGER}, #{messageContent,jdbcType=VARCHAR}, ",
        "#{messageStatus,jdbcType=CHAR}, #{addtime,jdbcType=TIMESTAMP}, ",
        "#{updatetime,jdbcType=TIMESTAMP})"
    })
    int insert(OfflineMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    int insertSelective(OfflineMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, message_from, message_to, message_content, message_status, addTime, updateTime",
        "from offline_message",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.imm.dao.OfflineMessageDao.BaseResultMap")
    OfflineMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OfflineMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    @Update({
        "update offline_message",
        "set message_from = #{messageFrom,jdbcType=INTEGER},",
          "message_to = #{messageTo,jdbcType=INTEGER},",
          "message_content = #{messageContent,jdbcType=VARCHAR},",
          "message_status = #{messageStatus,jdbcType=CHAR},",
          "addTime = #{addtime,jdbcType=TIMESTAMP},",
          "updateTime = #{updatetime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OfflineMessage record);
}