package com.imm.dao;

import com.imm.dao.base.MyBatisRepository;
import com.imm.model.po.OfflineMessage;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

import java.util.List;
@MyBatisRepository
@Repository
public interface OfflineMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    @Delete({
        "delete from offline_message",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    @Insert({
        "insert into offline_message (id, messagefrom, ",
        "messageto, messagecontent, ",
        "messagestatus, addtime, ",
        "updatetime)",
        "values (#{id,jdbcType=INTEGER}, #{messagefrom,jdbcType=INTEGER}, ",
        "#{messageto,jdbcType=INTEGER}, #{messagecontent,jdbcType=VARCHAR}, ",
        "#{messagestatus,jdbcType=CHAR}, #{addtime,jdbcType=TIMESTAMP}, ",
        "#{updatetime,jdbcType=TIMESTAMP})"
    })
    int insert(OfflineMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    int insertSelective(OfflineMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, messagefrom, messageto, messagecontent, messagestatus, addtime, updatetime",
        "from offline_message",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.imm.dao.OfflineMessageMapper.BaseResultMap")
    OfflineMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OfflineMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_message
     *
     * @mbg.generated
     */
    @Update({
        "update offline_message",
        "set messagefrom = #{messagefrom,jdbcType=INTEGER},",
          "messageto = #{messageto,jdbcType=INTEGER},",
          "messagecontent = #{messagecontent,jdbcType=VARCHAR},",
          "messagestatus = #{messagestatus,jdbcType=CHAR},",
          "addtime = #{addtime,jdbcType=TIMESTAMP},",
          "updatetime = #{updatetime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OfflineMessage record);

    List<OfflineMessage> getOfflineMessageByAccout(@Param("account") String account, @Param("status") String status);
}