package com.imm.dao;

import com.imm.dao.base.MyBatisRepository;
import com.imm.model.po.Friends;
import com.imm.model.po.Relation;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Repository;

import java.util.List;
@MyBatisRepository
@Repository
public interface RelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    @Delete({
        "delete from relation",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    @Insert({
        "insert into relation (id, userid, ",
        "friendid, status, ",
        "addtime, updatetime)",
        "values (#{id,jdbcType=INTEGER}, #{userid,jdbcType=VARCHAR}, ",
        "#{friendid,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{addtime,jdbcType=TIMESTAMP}, #{updatetime,jdbcType=TIMESTAMP})"
    })
    int insert(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    int insertSelective(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, userid, friendid, status, addtime, updatetime",
        "from relation",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.imm.dao.RelationMapper.BaseResultMap")
    Relation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    @Update({
        "update relation",
        "set userid = #{userid,jdbcType=VARCHAR},",
          "friendid = #{friendid,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "addtime = #{addtime,jdbcType=TIMESTAMP},",
          "updatetime = #{updatetime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Relation record);

    List<Friends> findFriendList(@Param("account") String account);
}