package com.imm.dao;

import com.imm.dao.base.MyBatisRepository;
import com.imm.model.Relation;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Component;

@Component
@MyBatisRepository
public interface RelationDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    @Delete({
        "delete from relation",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    @Insert({
        "insert into relation (id, user_id, ",
        "friend_id, status, addTime, ",
        "updateTime)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{friendId,jdbcType=INTEGER}, #{status,jdbcType=CHAR}, #{addtime,jdbcType=TIMESTAMP}, ",
        "#{updatetime,jdbcType=TIMESTAMP})"
    })
    int insert(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    int insertSelective(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, user_id, friend_id, status, addTime, updateTime",
        "from relation",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.imm.dao.RelationDao.BaseResultMap")
    Relation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated
     */
    @Update({
        "update relation",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "friend_id = #{friendId,jdbcType=INTEGER},",
          "status = #{status,jdbcType=CHAR},",
          "addTime = #{addtime,jdbcType=TIMESTAMP},",
          "updateTime = #{updatetime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Relation record);
}