package com.imm.dao;

import com.imm.dao.base.MyBatisRepository;
import com.imm.model.po.Synch;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Repository;

import java.util.List;

@MyBatisRepository
@Repository
public interface SynchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synch
     *
     * @mbg.generated
     */
    @Delete({
        "delete from synch",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synch
     *
     * @mbg.generated
     */
    @Insert({
        "insert into synch (id, account, ",
        "transaction_code, transaction_id, ",
        "transaction_event, transaction_status, ",
        "addtime)",
        "values (#{id,jdbcType=INTEGER}, #{account,jdbcType=VARCHAR}, ",
        "#{transactionCode,jdbcType=VARCHAR}, #{transactionId,jdbcType=INTEGER}, ",
        "#{transactionEvent,jdbcType=VARCHAR}, #{transactionStatus,jdbcType=TINYINT}, ",
        "#{addtime,jdbcType=TIMESTAMP})"
    })
    int insert(Synch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synch
     *
     * @mbg.generated
     */
    int insertSelective(Synch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synch
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, account, transaction_code, transaction_id, transaction_event, transaction_status, ",
        "addtime",
        "from synch",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.imm.dao.SynchMapper.BaseResultMap")
    Synch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synch
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Synch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table synch
     *
     * @mbg.generated
     */
    @Update({
        "update synch",
        "set account = #{account,jdbcType=VARCHAR},",
          "transaction_code = #{transactionCode,jdbcType=VARCHAR},",
          "transaction_id = #{transactionId,jdbcType=INTEGER},",
          "transaction_event = #{transactionEvent,jdbcType=VARCHAR},",
          "transaction_status = #{transactionStatus,jdbcType=TINYINT},",
          "addtime = #{addtime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Synch record);

    List<Synch> getSynchListByAccount(@Param("account")String account);
}